"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from django.urls import reverse_lazy

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# Raises an error if SECRET_KEY is missing
if not SECRET_KEY:
    raise ValueError("No SECRET_KEY set for Django application. Please check your .env file.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# ==========================================
# Variables de entorno IA (Regla 6.1 llm_context)
# ==========================================
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tailwind',
    "apps.library",
    "apps.search",
    "theme",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Tipo de campo de clave primaria por defecto para todas las aplicaciones
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

UNFOLD = {
    "SITE_TITLE": "Biblioteca Universitaria",
    "SITE_HEADER": "Sistema de Gestión",
    "SITE_URL": "/",
    "SIDEBAR": {
        # Muestra barra de búsqueda en la navegación lateral
        "show_search": True,
        # Desactivamos el enlace "Ver todas las aplicaciones" para forzar el menú controlado
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Gestión Bibliotecaria",
                "items": [
                    {
                        "title": "Libros",
                        "icon": "menu_book",
                        "link": reverse_lazy("admin:library_book_changelist"),
                    },
                    {
                        "title": "Préstamos",
                        "icon": "bookmark",
                        "link": reverse_lazy("admin:library_loan_changelist"),
                    },
                    {
                        "title": "Estudiantes",
                        "icon": "person",
                        "link": reverse_lazy("admin:library_student_changelist"),
                    },
                    {
                        "title": "Registro de Auditoría",
                        "icon": "history",
                        "link": reverse_lazy("admin:library_auditlog_changelist"),
                    },
                ],
            },
            {
                # Esta sección SOLO es visible para superusuarios (Administradores)
                "title": "Administración del Sistema",
                "items": [
                    {
                        "title": "Usuarios",
                        "icon": "manage_accounts",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Bibliotecarios",
                        "icon": "badge",
                        "link": reverse_lazy("admin:library_librarian_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                    {
                        "title": "Grupos y Roles",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": lambda request: request.user.is_superuser,
                    },
                ],
            },
        ],
    },
}

# Configuración de Tailwind CSS
TAILWIND_APP_NAME = 'theme'
INTERNAL_IPS = ['127.0.0.1']
NPM_BIN_PATH = r'C:\Program Files\nodejs\npm.cmd'

# Redirecciones de autenticación
LOGIN_URL = '/'
LOGIN_REDIRECT_URL = '/catalogo/'
LOGOUT_REDIRECT_URL = '/'
